
# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/nimbusdrive
spring.datasource.username=${NIMBUSDRIVE_DB_USERNAME}
spring.datasource.password=${NIMBUSDRIVE_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Application Configuration
spring.application.name=nimbusdrive
server.port=8080

# JWT
jwt.secret=${NIMBUSDRIVE_JWT_SECRET_KEY}

# 1 day in milliseconds
jwt.expiration=86400000

# AWS S3 Configuration
aws.accessKey=${NIMBUSDRIVE_AWS_ACCESS_KEY}
aws.secretKey=${NIMBUSDRIVE_AWS_SECRET_KEY}
aws.bucket=${NIMBUSDRIVE_AWS_BUCKET}
aws.region=${NIMBUSDRIVE_AWS_REGION}